spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sample_entity
    username: root
    password: root
